// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyFirstEfCoreApp.Migrations
{
    [DbContext(typeof(PlantFlowDbContext))]
    [Migration("20260825221126_AddQualityInspectionOneToOne")]
    partial class AddQualityInspectionOneToOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("QualityInspection", b =>
                {
                    b.Property<int>("QualityInspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QualityInspectionId"));

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PassedInspection")
                        .HasColumnType("bit");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("QualityInspectionId");

                    b.HasIndex("WorkOrderId")
                        .IsUnique();

                    b.ToTable("QualityInspection");
                });

            modelBuilder.Entity("WorkOrder", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkOrderId"));

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkOrderId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("WorkOrder", "workOrder")
                        .WithMany("Product")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("workOrder");
                });

            modelBuilder.Entity("QualityInspection", b =>
                {
                    b.HasOne("WorkOrder", "WorkOrder")
                        .WithOne("QualityInspection")
                        .HasForeignKey("QualityInspection", "WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("WorkOrder", b =>
                {
                    b.Navigation("Product");

                    b.Navigation("QualityInspection")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
