// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyFirstEfCoreApp.Migrations
{
    [DbContext(typeof(PlantFlowDbContext))]
    partial class PlantFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Operator", b =>
                {
                    b.Property<int>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperatorId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OperatorId");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("OperatorWorkStation", b =>
                {
                    b.Property<int>("OperatorsOperatorId")
                        .HasColumnType("int");

                    b.Property<int>("WorkStationsWorkStationId")
                        .HasColumnType("int");

                    b.HasKey("OperatorsOperatorId", "WorkStationsWorkStationId");

                    b.HasIndex("WorkStationsWorkStationId");

                    b.ToTable("OperatorWorkStation");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProductionLog", b =>
                {
                    b.Property<int>("ProductionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductionLogId"));

                    b.Property<DateTime>("LogTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantityProduced")
                        .HasColumnType("int");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("ProductionLogId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("ProductionLog");
                });

            modelBuilder.Entity("QualityInspection", b =>
                {
                    b.Property<int>("QualityInspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QualityInspectionId"));

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PassedInspection")
                        .HasColumnType("bit");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("QualityInspectionId");

                    b.HasIndex("WorkOrderId")
                        .IsUnique();

                    b.ToTable("QualityInspection");
                });

            modelBuilder.Entity("WorkOrder", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkOrderId"));

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkOrderId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("WorkStation", b =>
                {
                    b.Property<int>("WorkStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkStationId"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkStationId");

                    b.ToTable("WorkStations");
                });

            modelBuilder.Entity("OperatorWorkStation", b =>
                {
                    b.HasOne("Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorsOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkStation", null)
                        .WithMany()
                        .HasForeignKey("WorkStationsWorkStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("WorkOrder", "workOrder")
                        .WithMany("Product")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("workOrder");
                });

            modelBuilder.Entity("ProductionLog", b =>
                {
                    b.HasOne("WorkOrder", "WorkOrder")
                        .WithMany("ProductionLogs")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("QualityInspection", b =>
                {
                    b.HasOne("WorkOrder", "WorkOrder")
                        .WithOne("QualityInspection")
                        .HasForeignKey("QualityInspection", "WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("WorkOrder", b =>
                {
                    b.Navigation("Product");

                    b.Navigation("ProductionLogs");

                    b.Navigation("QualityInspection")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
